<?php

namespace AppBundle\Repository;

/**
 * GoederenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoederenRepository extends \Doctrine\ORM\EntityRepository
{
}
